crud/crud/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crud/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('<slug:category_slug>/', views.meal_list, name='meal_list_by_category'),
    path('<int:id>/<slug:slug>/', views.meal_detail, name='meal_detail'),
]

crud/shop/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.urls.base import reverse

# Create your models here.

""" 
Models for the Restuarant CRUD App
-Meals
-Category
-Menu
"""

class Category(models.Model):
    name = models.CharField(max_length=191, db_index=True)
    slug = models.SlugField(max_length=191, unique=True)

    def get_absolute_url(self):
        return reverse("shop:meal_list_by_category", args=[self.slug])
    
    class Meta:

        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    

class Meal(models.Model):
    category = models.ForeignKey(Category, related_name='meals', on_delete=CASCADE)
    name = models.CharField(max_length=191, db_index=True)
    slug = models.SlugField(max_length=191, db_index=True)
    image = models.ImageField(upload_to='meals/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("shop:meal_detail", args=[self.id, self.slug])
    

    class Meta:

        ordering = ('name',)
        index_together = (('id', 'slug'))

    def __str__(self):
        return self.name

crud/shop/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category, Meal

# Create your views here.

def meal_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    meals = Meal.objects.filter(available=True)
    
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        meals = meals.filter(category=category)
    
    return render(
        request, 'shop/meal/list.html',{
            'category': category,
            'categories': categories,
            'meals': meals,
            }
        )

def meal_detail(request, id, slug):
    meal = get_object_or_404(Meal, id=id, slug=slug, available=True)

    return render(request, 'shop/meal/detail.html', {'meal': meal})

crud/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
      <div class="cart">
            Your cart is empty.
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

crud/shop/templates/shop/meal/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ meal.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if meal.image %}{{ meal.image.url }}{% else %}
    {% static "img/no_image.png" %}{% endif %}">
    <h1>{{ meal.name }}</h1>
    <h2>
      <a href="{{ meal.category.get_absolute_url }}">
        {{ meal.category }}
      </a>
    </h2>
    <p class="price">N{{ meal.price }}</p>

    {{ meal.description|linebreaks }}
  </div>
{% endblock %}

crud/shop/templates/shop/meal/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Meals{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url "shop:meal_list" %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Meals{% endif %}</h1>
    {% for meal in meals %}
      <div class="item">
        <a href="{{ meal.get_absolute_url }}">
          <img src="{% if meal.image %}{{ meal.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </a>
        <a href="{{ meal.get_absolute_url }}">{{ meal.name }}</a>
        <br>
        N{{ meal.price }}
      </div>
    {% endfor %}
  </div>
{% endblock %}